#!/bin/bash

#Run with:
#eval "$(curl -fsSL -H 'Cache-Control: no-cache' https://git.atomjump.com/live-wiki-updates.git/update)"

#Get latest version of loop-server
sudo git -C /jet/www/default/vendor/atomjump/loop-server pull

#Update the main livewiki
sudo git -C /jet/www/default/livewiki pull

#Update the notifications plugin
sudo git -C /jet/www/default/vendor/atomjump/loop-server/plugins/notifications pull

#Update the large_emoticons plugin
sudo git -C /jet/www/default/vendor/atomjump/loop-server/plugins/emoticons_large pull




#Update the npm version for sentiment analysis
curl -sL https://deb.nodesource.com/setup_12.x | sudo bash -
sudo apt-get install -y nodejs
sudo npm --prefix /jet/www/default/vendor/atomjump/loop-server/node install /jet/www/default/vendor/atomjump/loop-server/node



#Add a sentiment analysis crontab - but only do this once.
if test -f ~/sentiment-setup.txt; then
	echo "Sentiment has already been set up.\n";
else
	touch ~/sentiment-setup.txt 
	line="*/1 * * * *     /usr/bin/node /jet/www/default/vendor/atomjump/loop-server/node/sentiment.js"; (sudo crontab -u root -l; echo "$line" ) | sudo crontab -u root -
	echo "Sentiment checker has been added to your crontab.";
fi

#Update notifications
sudo /jet/bin/php /jet/www/default/vendor/atomjump/loop-server/plugins/notifications/install.php
sudo chmod 777 /jet/www/default/vendor/atomjump/loop-server/plugins/notifications/outgoing


sudo rm update-language.txt
sudo rm update-language.php
sudo curl -fsSL -H 'Cache-Control: no-cache' https://git.atomjump.com/live-wiki-updates.git/update-language.txt > update-language.txt

sudo mv update-language.txt update-language.php 
sudo /jet/bin/php update-language.php notifications


while true; do
    read -p "Do you wish to update to the latest version of the languages translations from AtomJump (15 languages) (Enter yes or no)?" yn
    case $yn in
        [Yy]* ) #Get the latest language file with all languages
				sudo mv /jet/www/default/vendor/atomjump/loop-server/config/messages.json /jet/www/default/vendor/atomjump/loop-server/config/messages-old-backup.json;
				sudo wget https://git.atomjump.com/change_language.git/languages/en_bg_ch_cht_de_es_fr_hi_in_it_jp_ko_pu_ru/messages.json -P /jet/www/default/vendor/atomjump/loop-server/config/

				#Get the latest language .js entries
				sudo rm chat-inner.js 
				sudo wget https://git.atomjump.com/change_language.git/languages/en_bg_ch_cht_de_es_fr_hi_in_it_jp_ko_pu_ru/chat-inner.js 

				sudo rm chats.js 
				sudo wget https://git.atomjump.com/change_language.git/languages/en_bg_ch_cht_de_es_fr_hi_in_it_jp_ko_pu_ru/chats.js


				#/jet/www/default/livewiki/js/chat-1.0.9.js

				#Get a php script and run this to replace /jet/www/default/livewiki/js/chat-*.js

				sudo /jet/bin/php update-language.php languages
        		break;;
        [Nn]* ) break;;
        * ) echo "Please answer yes or no.";;
    esac
done




while true; do
    read -p "Do you wish to install popup notifications for the app (Enter yes or no)?" yn
    case $yn in
        [Yy]* ) #Install popup notifications
        
        	#MedImage install steps
        	sudo npm install pm2@latest -g
			sudo npm install medimage -g
			cd "$(npm prefix -global)/lib/node_modules/medimage/" 
			sudo cp config-original/linORIGINALconfig.json config.json
			sudo cp addons/configORIGINAL.json addons/config.json
			sudo pm2 delete 'medimage-server'
			sudo pm2 start npm --name "medimage-server" -- start ./medimage-server.sh; cd ~
			sudo pm2 save
			
			sudo ufw allow 5566/tcp

			#Install app
			git clone https://src.atomjump.com/atomjump/messaging app
			cd app
			git checkout browser-production
			
			sudo npm install -g cordova
			sudo cordova platform add browser
			sudo ufw allow 8000/tcp			
			sudo pm2 delete 'sudo cordova run browser'
			sudo pm2 start 'sudo cordova run browser'
			sudo pm2 save
        
        	sudo pm2 startup
        	echo "\n\n";
        	sleep 5
        
        	#Update the notifications plugin and overwrite the config file
        	cd ~
			sudo git -C /jet/www/default/vendor/atomjump/loop-server/plugins/notifications pull
			sudo /jet/bin/php /jet/www/default/vendor/atomjump/loop-server/plugins/notifications/install.php
			sudo chmod 777 /jet/www/default/vendor/atomjump/loop-server/plugins/notifications/outgoing
			sudo cp /jet/www/default/vendor/atomjump/loop-server/plugins/notifications/config/config.json /jet/www/default/vendor/atomjump/loop-server/plugins/notifications/config/config-old.json 
	
        	
        	#And explain to the user that they need to add two extra ports
        	echo "\n\nAtomJump Notifications Installation successful!\n\nInside your 'Virtual Box Settings > Network > Advanced > Port forwarding', you will need to add two new ports:\n1. Host TCP 127.0.0.1 Port: 8000 >> Guest IP 10.0.2.15 Port:8000\n2. Host TCP 127.0.0.1 Port: 5566 Guest IP 10.0.2.15 Port:5566\n\n(replace 10.0.2.15 with your own IP addresses, if necessary)";
        	echo "You should also configure your email and notifications below...\n";
        	
        break;;
        [Nn]* ) break;;
        * ) echo "Please answer yes or no.";;
    esac
done


#Get the notifications update script
sudo rm update-notifications-config.txt
sudo rm update-notifications-config.php
sudo curl -fsSL -H 'Cache-Control: no-cache' https://git.atomjump.com/live-wiki-updates.git/update-notifications-config.txt > update-notifications-config.txt
sudo mv update-notifications-config.txt update-notifications-config.php 

#Ask on both email setup and notifications setup
sudo /jet/bin/php update-notifications-config.php 		
