#!/bin/bash

#Run with:
#eval "$(curl -fsSL -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/atomjump/live-wiki-updates/master/update)"

#Get latest version of loop-server
sudo git -C /jet/www/default/vendor/atomjump/loop-server pull

#Update the main livewiki
sudo git -C /jet/www/default/livewiki pull

#Update the npm version for sentiment analysis
curl -sL https://deb.nodesource.com/setup_12.x | sudo bash -
sudo apt-get install -y nodejs
sudo npm install -g /jet/www/default/vendor/atomjump/loop-server/node
sudo npm --prefix /jet/www/default/vendor/atomjump/loop-server/node install /jet/www/default/vendor/atomjump/loop-server/node

#Add a sentiment analysis crontab - but only do this once.
line="*/1 * * * *     /usr/bin/node /jet/www/default/vendor/atomjump/loop-server/node/sentiment.js"; (sudo crontab -u root -l; echo "$line" ) | sudo crontab -u root -
